# Generated by Django 4.1.4 on 2022-12-30 08:13

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30, unique=True)),
                ('body', mdeditor.fields.MDTextField()),
            ],
        ),
        migrations.CreateModel(
            name='FmarkSon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmark.fmark')),
            ],
        ),
    ]
