# Generated by Django 4.1.4 on 2022-12-18 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_nature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_nature_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_sector_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota_num', models.FloatField()),
                ('quota_date', models.DateField()),
                ('quota_finish', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftrace.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftrace.customer_nature'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftrace.customer_sector'),
        ),
        migrations.CreateModel(
            name='Booker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker_name', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftrace.customer')),
            ],
        ),
    ]
