# Generated by Django 4.1.4 on 2022-12-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftrace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_sector',
            name='sort_index',
            field=models.IntegerField(default=0),
        ),
    ]
