# Generated by Django 4.1.4 on 2022-12-20 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftrace', '0002_customer_sector_sort_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_cargo_name', models.CharField(max_length=30)),
                ('sort_index', models.IntegerField(default=0)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftrace.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_cargo_sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_cargo_sector_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_sector',
        ),
        migrations.RemoveField(
            model_name='quata',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer_sector',
        ),
        migrations.AddField(
            model_name='customer_cargo',
            name='customer_cargo_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ftrace.customer_cargo_sector'),
        ),
        migrations.AddField(
            model_name='quata',
            name='customer_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ftrace.customer_cargo'),
        ),
    ]
