# Generated by Django 4.1.4 on 2022-12-21 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftrace', '0003_cargo_customer_cargo_customer_cargo_sector_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source_sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_sector_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer_cargo',
            name='customer_cargo_sector',
        ),
        migrations.AddField(
            model_name='customer_cargo',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ftrace.customer'),
        ),
        migrations.AlterField(
            model_name='customer_cargo',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ftrace.cargo'),
        ),
        migrations.DeleteModel(
            name='Customer_cargo_sector',
        ),
        migrations.AddField(
            model_name='customer_cargo',
            name='source_sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ftrace.source_sector'),
        ),
    ]
