# Generated by Django 4.1.4 on 2022-12-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftrace', '0004_source_sector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ftrace.customer_nature'),
        ),
    ]
