# Generated by Django 4.1.4 on 2022-12-24 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftrace', '0007_remove_source_customer_sourceship_source_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='source_sector',
            name='customer_nature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ftrace.customer_nature'),
        ),
    ]
