# Generated by Django 4.1.4 on 2022-12-24 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ftrace', '0008_source_sector_customer_nature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quata',
            name='source',
        ),
        migrations.AddField(
            model_name='quata',
            name='sourceship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ftrace.sourceship'),
        ),
    ]
