# Generated by Django 4.1.4 on 2022-12-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftrace', '0009_remove_quata_source_quata_sourceship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booker',
            name='booker_name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
